from backend.constants.messages import (
    ACCOUNT_INACTIVE_MESSAGE,
    ACCOUNT_PENDING_APPROVAL_MESSAGE,
    AUTHENTICATION_ERROR_MESSAGE,
    DOCTOR_NOT_FOUND_MESSAGE,
    EMAIL_ALREADY_REGISTERED_MESSAGE,
    INCORRECT_EMAIL_OR_PASSWORD_MESSAGE,
    INSUFFICIENT_PRIVILEGES_MESSAGE,
)
from backend.constants.roles import ALLOWED_REGISTRATION_ROLES, ROLE_DOCTOR, ROLE_PATIENT

__all__ = [
    "ACCOUNT_INACTIVE_MESSAGE",
    "ACCOUNT_PENDING_APPROVAL_MESSAGE",
    "ALLOWED_REGISTRATION_ROLES",
    "AUTHENTICATION_ERROR_MESSAGE",
    "DOCTOR_NOT_FOUND_MESSAGE",
    "EMAIL_ALREADY_REGISTERED_MESSAGE",
    "INCORRECT_EMAIL_OR_PASSWORD_MESSAGE",
    "INSUFFICIENT_PRIVILEGES_MESSAGE",
    "ROLE_DOCTOR",
    "ROLE_PATIENT",
]
