from backend.constants.messages import (
    ACCOUNT_INACTIVE_MESSAGE,
    ACCOUNT_PENDING_APPROVAL_MESSAGE,
    AUTHENTICATION_ERROR_MESSAGE,
    DOCTOR_NOT_FOUND_MESSAGE,
    EMAIL_ALREADY_REGISTERED_MESSAGE,
    INCORRECT_EMAIL_OR_PASSWORD_MESSAGE,
    INSUFFICIENT_PRIVILEGES_MESSAGE,
    SLOT_NOT_FOUND_MESSAGE,
    SLOT_ALREADY_BOOKED_MESSAGE,
    PAST_SLOT_BOOKING_MESSAGE,
    APPOINTMENT_NOT_FOUND_MESSAGE,
    APPOINTMENT_ALREADY_PAID_MESSAGE,
    APPOINTMENT_CANNOT_BE_CANCELLED_MESSAGE,
    CANCELLATION_TIME_LIMIT_EXCEEDED_MESSAGE,
)
from backend.constants.roles import ALLOWED_REGISTRATION_ROLES, ROLE_DOCTOR, ROLE_PATIENT
from backend.constants.appointment import CANCELLATION_WINDOW_HOURS

__all__ = [
    "ACCOUNT_INACTIVE_MESSAGE",
    "ACCOUNT_PENDING_APPROVAL_MESSAGE",
    "ALLOWED_REGISTRATION_ROLES",
    "AUTHENTICATION_ERROR_MESSAGE",
    "DOCTOR_NOT_FOUND_MESSAGE",
    "EMAIL_ALREADY_REGISTERED_MESSAGE",
    "INCORRECT_EMAIL_OR_PASSWORD_MESSAGE",
    "INSUFFICIENT_PRIVILEGES_MESSAGE",
    "ROLE_DOCTOR",
    "ROLE_PATIENT",
    "SLOT_NOT_FOUND_MESSAGE",
    "SLOT_ALREADY_BOOKED_MESSAGE",
    "PAST_SLOT_BOOKING_MESSAGE",
    "APPOINTMENT_NOT_FOUND_MESSAGE",
    "APPOINTMENT_ALREADY_PAID_MESSAGE",
    "APPOINTMENT_CANNOT_BE_CANCELLED_MESSAGE",
    "CANCELLATION_TIME_LIMIT_EXCEEDED_MESSAGE",
    "CANCELLATION_WINDOW_HOURS",
]
